// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#pragma once

#include <frc2/command/SubsystemBase.h>
#include <ctre/phoenix/motorcontrol/can/TalonFX.h> //falcon 500 motors with talon fx's built in

#include "Constants.h"

class Shooter: public frc2::SubsystemBase {

private:
    ctre::phoenix::motorcontrol::can::TalonFX m_shooterMotor1{ShooterConstants::kShooterMotor1Port};
    ctre::phoenix::motorcontrol::can::TalonFX m_shooterMotor2{ShooterConstants::kShooterMotor2Port};

public:
    Shooter();

    void Periodic() override;
    void SimulationPeriodic() override;
    void Shoot();
    void ShooterStop();
};