// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "subsystems/Climber.h"

#include <frc/smartdashboard/SmartDashboard.h>
#include <wpi/raw_ostream.h> // for wpi outs()


Climber::Climber(){
    SetName("Climber");
    SetSubsystem("Climber");

    //AddChild("ClimberMotor1", &m_climberMotor1);
    m_climberMotor1.SetInverted(true);

    //AddChild("ClimberMotor2", &m_climberMotor2);
    m_climberMotor2.SetInverted(true);

    //AddChild("ClimberMotors", &m_climberMotors);
}

void Climber::Periodic() {
    // Put code here to be run every loop
}

void Climber::SimulationPeriodic() {
}

// Put methods for controlling this subsystem here and call from commands

void Climber::Raise(){ 
    // Run Climber
        m_climberMotor1.Set(-0.35);
        m_climberMotor2.Set(-0.35); 
} 

void Climber::Lower(){
    // Run Expel
    m_climberMotor1.Set(0.35);
    m_climberMotor2.Set(0.35);
}

void Climber::ClimberStop(){
    // stop the Climber motor
    m_climberMotor1.Set(0.0);
    m_climberMotor2.Set(0.0);
    
}