// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

#include "subsystems/Vision.h"

#include <frc/smartdashboard/SmartDashboard.h>
#include <wpi/raw_ostream.h> // for wpi outs()

Vision::Vision(){
    SetName("Vision");
    SetSubsystem("Vision");
}

void Vision::Periodic() {
    // Put code here to be run every loop
}

void Vision::SimulationPeriodic() {
}

// Put methods for controlling this subsystem here and call from commands

void Vision::VisionScan(){ 
        photon::PhotonPipelineResult result = camera.GetLatestResult();
        photon::PhotonTrackedTarget target = result.GetBestTarget();
} 

void Vision::VisionTrack(){
        if (result.HasTargets()) {
            frc::SmartDashboard::PutNumber("PhotonVision Target ID", target.GetFiducialId());
        }
}